### PR TITLE
Version fix

### PR DESCRIPTION
**Pull request by erg**
Hey, nice work!

There are some problems, mostly that it depends on an old version of Polymer. I think this should fix that issue.

Additionally, the name in bower is `polymer-star-rating` and so I have updated the `name` field to reflect this.

Finally, it would be nice if you opened an issue tracker for the project on github.

Thanks!

### CODE REVIEW

**Comment by ionelmc** [comment]
Just asking - shouldn't the version restriction be completely removed ? Eg:

```
"polymer": "Polymer/polymer"
```

**Comment by erg** [comment]
@ionelmc If you look at the `bower.json` for other polymer components, they depend on the `#master` branch.

**Comment by ionelmc** [comment]
Well I've opened https://github.com/webcomponents/polymer-boilerplate/issues/19 - probably a better place to argue about this.

**Comment by erg** [comment]
I'm getting this no matter what I do locally, and then it tries to pull in `Polymer#~0.2.4` (the old version that my local git no longer refers to):

`bower polymer-star-rating#*           mismatch Version declared in the json (0.0.0) is different than the resolved one (0.1.4)`

my `bower.json`:

```
  "dependencies": {
    ...
    "polymer-star-rating": "/Users/erg/polymer/polymer-star-rating"
  }
```

It seems that `bower` trusts the published repositories over the local ones, and `polymer-star-rating` currently has version `0.0.0` because @manoelneto didn't change it from the cloned repository.

1) Where is the quality control?
2) Why doesn't `bower` let my local repository override the published one? If I remove the `.git` directory then everything is great, but if `bower` sees my local repo is a clone of one in its published list, then it ignores my local repo? I'm sure there's something to fix here as it's not intuitive what's happening or why it won't just install my fixed repo.

Kind of frustrating.

**Comment by ionelmc** [comment]
@erg Also, `master` won't match 0.3.4 (the latest release).

**Comment by manoelneto** [comment]
Sorry men. I did this for study and i didnt know this issues. Thanks to all.

**Comment by erg** [comment]
Hey @manoelneto,

I'm still getting the `bower polymer-star-rating#*                   mismatch Version declared in the json (0.0.0) is different than the resolved one (0.1.4)` line.

Not sure how to fix that one. It looks like bower is still caching the old version somewhere. Maybe since you had a version before it will always need one? In that case, add the `"version": "0.1.5"` line back to `bower.json` or something.

Also, can you make an `issues` section for this project? Thanks!

**Comment by erg** [comment]
@manoelneto Np, I'm torn between just writing my own or trying to fix yours and contribute it back to the community. I'm still learning how all this works.

**Comment by ionelmc** [comment]
I think you need to tag a new release and do `bower release`

Thanks,
-- Ionel M.

**Comment by manoelneto** [comment]
Hey guys, I`ve added Issues tab to this project and I`ve made a release. Can you check it now please?

Thanks.

**Pull request merged**
